# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



# make a fibonacci sequence
fib_sequence = [1,2]

sum = 2
while fib_sequence[-1] + fib_sequence[-2] < 4_000_000  
  fib_sequence << fib_sequence[-1] + fib_sequence[-2]
  if fib_sequence[-1].even?
    sum += fib_sequence[-1]
  end
end

p sum